Data Analysis -- Numpy Library

- Numpy is used for working with arrays in python 
- Created by Travis Oliphant in 2005
- It is an open source project

In [ ]:
import numpy as np
# 1-d Array
a = np.array([1,2,3,4,5,6])
b = np.array([2,3,4,5,6])
print(a)
print(b)

print(a.ndim) # Finds the dimensions of the array
print(b.ndim)

[1 2 3 4 5 6]
[2 3 4 5 6]
1
1


In [ ]:
import numpy as np
print(np.__version__)

#Creating a 0 Dimensional Array
arr = np.array(42)
print(arr)
print(arr.ndim)

2.1.0
42
0


In [ ]:
#Creating a 2d array
arr1= np.array([[1,2],[5,6]])
print(arr1)
print(type(arr1))

print(arr1.shape)
print(arr1.dtype)

np.arange(5)
np.arange(3,30,2)


[[1 2]
 [5 6]]
<class 'numpy.ndarray'>
(2, 2)
int64


array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
np.random.randint(10,30, size=(2,5))

array([[14, 29, 22, 11, 20],
       [22, 10, 27, 13, 16]], dtype=int32)

In [30]:
x = np.array([[2,3,4],
             [3,4,5],
             [7,8,9]])
print(x)
y = np.array([[1,2,3],
              [9,0,3],
              [3,4,5]])
print(y)
print(x[2,1] + y[2,1])
print(x[0,2] + y[1,2])

#matrix multiplication
print(x@y)

[[2 3 4]
 [3 4 5]
 [7 8 9]]
[[1 2 3]
 [9 0 3]
 [3 4 5]]
12
7
[[ 41  20  35]
 [ 54  26  46]
 [106  50  90]]


In [26]:
print(x.dot(y))

[[ 41  20  35]
 [ 54  26  46]
 [106  50  90]]


In [ ]:
print(x*y)

[[ 2  6 12]
 [27  0 15]
 [21 32 45]]


In [ ]:
x.prod() #product of all elements

np.int64(725760)

In [ ]:
x.sum()

np.float64(5.0)

In [34]:
x.mean()

np.float64(5.0)

In [ ]:
x.mean(axis=0) #mean of each column

array([4., 5., 6.])

In [36]:
x.mean(axis=1)

array([3., 4., 8.])

In [39]:
print(x.var()) 
print(x.std())
print(x.max())

5.333333333333333
2.309401076758503
9


In [48]:
z = np.array([1,2,3,2,3,4,5,7,8,9])
print(np.median(z))
print(np.percentile(z, 25))

3.5
2.25


In [49]:
ar = np.array([[16,44,46,49],[10,12,22,21],[11,23,35,20],[43,23,22,12]])
print(ar)

[[16 44 46 49]
 [10 12 22 21]
 [11 23 35 20]
 [43 23 22 12]]


In [51]:
print('8x2')
print(ar.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 12]
 [22 21]
 [11 23]
 [35 20]
 [43 23]
 [22 12]]


In [53]:
print('2x3')
print(ar.reshape(2,8))

2x3
[[16 44 46 49 10 12 22 21]
 [11 23 35 20 43 23 22 12]]
